/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizeMergePdfRouteImport } from './routes/organize/merge-pdf'
import { Route as OptimizeOcrPdfRouteImport } from './routes/optimize/ocr-pdf'
import { Route as OptimizeCompressPdfRouteImport } from './routes/optimize/compress-pdf'
import { Route as EditEditPdfRouteImport } from './routes/edit/edit-pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizeMergePdfRoute = OrganizeMergePdfRouteImport.update({
  id: '/organize/merge-pdf',
  path: '/organize/merge-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeOcrPdfRoute = OptimizeOcrPdfRouteImport.update({
  id: '/optimize/ocr-pdf',
  path: '/optimize/ocr-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeCompressPdfRoute = OptimizeCompressPdfRouteImport.update({
  id: '/optimize/compress-pdf',
  path: '/optimize/compress-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEditPdfRoute = EditEditPdfRouteImport.update({
  id: '/edit/edit-pdf',
  path: '/edit/edit-pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edit/edit-pdf': typeof EditEditPdfRoute
  '/optimize/compress-pdf': typeof OptimizeCompressPdfRoute
  '/optimize/ocr-pdf': typeof OptimizeOcrPdfRoute
  '/organize/merge-pdf': typeof OrganizeMergePdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edit/edit-pdf': typeof EditEditPdfRoute
  '/optimize/compress-pdf': typeof OptimizeCompressPdfRoute
  '/optimize/ocr-pdf': typeof OptimizeOcrPdfRoute
  '/organize/merge-pdf': typeof OrganizeMergePdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edit/edit-pdf': typeof EditEditPdfRoute
  '/optimize/compress-pdf': typeof OptimizeCompressPdfRoute
  '/optimize/ocr-pdf': typeof OptimizeOcrPdfRoute
  '/organize/merge-pdf': typeof OrganizeMergePdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edit/edit-pdf'
    | '/optimize/compress-pdf'
    | '/optimize/ocr-pdf'
    | '/organize/merge-pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edit/edit-pdf'
    | '/optimize/compress-pdf'
    | '/optimize/ocr-pdf'
    | '/organize/merge-pdf'
  id:
    | '__root__'
    | '/'
    | '/edit/edit-pdf'
    | '/optimize/compress-pdf'
    | '/optimize/ocr-pdf'
    | '/organize/merge-pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditEditPdfRoute: typeof EditEditPdfRoute
  OptimizeCompressPdfRoute: typeof OptimizeCompressPdfRoute
  OptimizeOcrPdfRoute: typeof OptimizeOcrPdfRoute
  OrganizeMergePdfRoute: typeof OrganizeMergePdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organize/merge-pdf': {
      id: '/organize/merge-pdf'
      path: '/organize/merge-pdf'
      fullPath: '/organize/merge-pdf'
      preLoaderRoute: typeof OrganizeMergePdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize/ocr-pdf': {
      id: '/optimize/ocr-pdf'
      path: '/optimize/ocr-pdf'
      fullPath: '/optimize/ocr-pdf'
      preLoaderRoute: typeof OptimizeOcrPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize/compress-pdf': {
      id: '/optimize/compress-pdf'
      path: '/optimize/compress-pdf'
      fullPath: '/optimize/compress-pdf'
      preLoaderRoute: typeof OptimizeCompressPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/edit-pdf': {
      id: '/edit/edit-pdf'
      path: '/edit/edit-pdf'
      fullPath: '/edit/edit-pdf'
      preLoaderRoute: typeof EditEditPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditEditPdfRoute: EditEditPdfRoute,
  OptimizeCompressPdfRoute: OptimizeCompressPdfRoute,
  OptimizeOcrPdfRoute: OptimizeOcrPdfRoute,
  OrganizeMergePdfRoute: OrganizeMergePdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
